<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DMTQ_Tools.Components</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMTQ.Tools.Core\DMTQ.Tools.Core.csproj" />
  </ItemGroup>

</Project>
